spring:
  application:
    name: custom-mybatis
#  datasource:
    #      url: jdbc:postgresql://172.17.5.141:5432/gig_contract
    #      username: deliver_zhaopin
    #      password: deliver_zhaopin
    #      driver-class-name: org.postgresql.Driver
#    datasource1:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
#      username: root
#      password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    datasource2:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:zpdw
      username: 111
      password: 222

server:
  port: 8099
mybatis:
  mapper-locations: mapper/*.xml
